# SPDX-FileCopyrightText:
# SPDX-License-Identifier: Apache-2.0

version: 1

# Allow overriding the registry and image name with environment variables.
env:
  - REGISTRY={{ if index .Env "REGISTRY"  }}{{ .Env.REGISTRY }}{{ else }}ghcr.io/emissary-ingress{{ end }}
  - IMAGE_NAME={{ if index .Env "IMAGE_NAME"  }}{{ .Env.IMAGE_NAME }}{{ else }}emissary{{ end }}

before:
  hooks:
    - go mod tidy
    - rm -rf python/ambassador.version
    - make VERSION=v{{ .Version }} python/ambassador.version

builds:
  - id: busyambassador
    main: ./cmd/busyambassador
    binary: busyambassador
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    ids:
      - busyambassador
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Version }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=LIBARCH=x86_64"
    extra_files:
      - python

docker_manifests:
  - name_template: "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Version }}"
    create_flags:
      - --insecure
    push_flags:
      - --insecure

release:
  draft: true
  replace_existing_draft: true
  prerelease: true
  make_latest: false
