Reponame: code.arista.io/cv/emissary
Description: Fork of the open-source API gateway emissary-ingress, based on v3.x
Users:
  Maintainers:
  - thibault@arista.com
  Supervisor: thibault@arista.com
Epoch: 1
ObsoleteNames:
- gerrit.corp.arista.io/aristanetworks/emissary
